In [38]:
# Import packages
import pandas as pd
import numpy as np
from collections import defaultdict
import math

In [26]:

#  Import data
data = pd.read_csv("/Users/minnavainikainen/project1StatML/siren_data_train.csv", sep=",")
print(f"Data size: {data.memory_usage().sum() / 1e6:.2f} MB")
print("The first n rows in the data:")
data.head(10)

Data size: 0.59 MB
The first n rows in the data:

,near_fid,near_x,near_y,near_angle,heard,building,xcoor,ycoor,noise,in_vehicle,asleep,no_windows,age
0,2712,1.998301e+06,9.011692e+06,-171.588672,1,0,1999193.0,9011824,0,0,0,0,59
1,2721,1.928907e+06,8.954624e+06,-51.208102,1,0,1928298.0,8955382,0,0,0,0,29
2,297,2.026384e+06,8.256164e+06,39.018754,1,0,2025706.0,8255615,0,0,0,0,32
3,739,1.743184e+06,8.052652e+06,15.046022,1,0,1742935.0,8052585,0,0,0,0,36
4,1852,1.350375e+06,7.909850e+06,144.603170,1,0,1350807.0,7909543,0,0,0,0,55
5,2737,1.934971e+06,8.959613e+06,-159.477621,0,1,1938739.0,8961023,0,0,0,1,62
6,3692,1.327964e+06,7.940968e+06,18.712045,1,1,1327733.0,7940890,0,0,0,0,74
7,404,2.005312e+06,8.234592e+06,146.602179,1,0,2007113.0,8233405,0,0,0,0,24
8,133,2.010260e+06,8.244737e+06,91.888991,1,0,2010284.0,8244010,0,0,0,0,66
9,2003,1.339570e+06,7.892866e+06,160.654726,1,1,1340898.0,7892400,0,0,0,0,53

In [41]:
print("Overview of Numeric Variables")
numeric_columns = [col for col in data.columns]
data[numeric_columns].describe()

Overview of Numeric Variables

,near_fid,near_x,near_y,near_angle,heard,building,xcoor,ycoor,noise,in_vehicle,asleep,no_windows,age
count,5710.000000,5.710000e+03,5.710000e+03,5710.000000,5710.000000,5710.000000,5.710000e+03,5.710000e+03,5710.000000,5710.000000,5710.000000,5710.000000,5710.000000
mean,1888.705954,1.797385e+06,8.283496e+06,1.751993,0.760070,0.248687,1.796497e+06,8.283723e+06,0.190893,0.094046,0.006130,0.023643,50.635902
std,1320.046217,2.783430e+05,5.363099e+05,106.216736,0.427078,0.432290,2.789790e+05,5.369782e+05,0.393039,0.291918,0.078058,0.151947,18.630865
min,1.000000,1.244070e+06,7.430582e+06,-179.786267,0.000000,0.000000,1.244893e+06,7.432236e+06,0.000000,0.000000,0.000000,0.000000,18.000000
25%,538.000000,1.535191e+06,7.919606e+06,-90.278514,1.000000,0.000000,1.529848e+06,7.919276e+06,0.000000,0.000000,0.000000,0.000000,35.000000
50%,1901.000000,1.895376e+06,8.251327e+06,2.313685,1.000000,0.000000,1.891302e+06,8.251345e+06,0.000000,0.000000,0.000000,0.000000,50.000000
75%,2821.000000,2.003408e+06,8.368423e+06,95.330994,1.000000,0.000000,2.003743e+06,8.368852e+06,0.000000,0.000000,0.000000,0.000000,66.000000
max,4150.000000,2.686771e+06,1.040622e+07,179.992043,1.000000,1.000000,2.686256e+06,1.042743e+07,1.000000,1.000000,1.000000,1.000000,88.000000

In [ ]:
empty_list = []
loc_horn = 
dist_near = math.dist(loc_horn,loc_person)